
configfile: "config.yaml"


rule build_kallisto_index:
    input:
        ref_set_seq = "reference_set/sequences_filtered_7.fasta"
    output:
        kallisto_index = "reference_set" + "/sequences.kallisto_idx"
    shell:
        "kallisto index -i {output.kallisto_index} {input.ref_set_seq}"

rule create_benchmark_dir:
    shell:
        "mkdir benchmarks"

#mkdir benchmarks

rule generate_ww_data:
    input:
        ss_metadata =  config["metadata_ww"],
        ss_sequences =   config["sequences_ww"]

    params: 
        abudances = config['abundances'],
        vocs = config['vocs'],
        coverage = config['coverage']
    output:
        bench_dir = "benchmarks/ww_C.37vP.1"
    shell:
        "python ../../benchmarking/create_benchmarks.py --voc_perc {params.abudances} -m {input.ss_metadata} -fr {input.ss_sequences} -fv {params.vocs} -o {output.bench_dir} --total_cov {params.coverage}"


rule output_predictions:
    params:
        bootstraps = config["bootstraps"],
        min_ab = config["min_ab"],
        ref_set = "reference_set",
        dataset = "benchmarks/ww_C.37vP.1"
    shell:
        "bash ../../manuscript/run_kallisto_ref_sets_v1.sh {params.dataset} {params.bootstraps} {params.ref_set} {params.min_ab}"
